name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install pytest pytest-mock # Si tu utilises un fichier requirements.txt, tu peux aussi installer à partir de là
        pip install -r requirements.txt

    - name: Run tests
      run: pytest testing.py
